//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS.Base_BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HIS.Base_BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;GWI_HIS&gt;
        ///  &lt;门诊经管&gt;
        ///    &lt;Parameters  code=&quot;001&quot; name=&quot;控制是否允许录入POS金额&quot; notes=&quot;0-允许；1-不允许&quot; deptid=&quot;0&quot;&gt;0&lt;/Parameters&gt;
        ///    &lt;Parameters  code=&quot;002&quot; name=&quot;控制是否允许手工录入医保农合支付金额&quot; notes=&quot;0-允许；1-不允许&quot; deptid=&quot;0&quot;&gt;0&lt;/Parameters&gt;
        ///    &lt;Parameters  code=&quot;003&quot; name=&quot;发票打印内容显示方式&quot; notes=&quot;0-打印明细；1-打印发票项目&quot; deptid=&quot;0&quot;&gt;0&lt;/Parameters&gt;
        ///    &lt;Parameters  code=&quot;004&quot; name=&quot;发票打印前预览&quot; notes=&quot;0-允许预览；1-不预览&quot; deptid=&quot;0&quot;&gt;1&lt;/Parameters&gt;
        ///    &lt;Parameters  code=&quot;005&quot; name=&quot;就诊号最大长度&quot; notes=&quot;&quot; deptid=&quot;0&quot;&gt;12&lt;/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
    }
}
