//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.1432。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CHIServiceHttpBinding", Namespace="http://webservice.ty.com/CHIService")]
public partial class CHIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getYfjzInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkHthOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_Medical_InspectionInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadMzInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_Clinic_Medical_RecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_Mzcf_RecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadCrbInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getZyBcInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPatientInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getMbInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getZyryInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getZhxxOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadMbInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_To_Hospital_RecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTjrqOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkZyOperationCompleted;
    
    private System.Threading.SendOrPostCallback getZycyInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadZxsrOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTjInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_Zycf_RecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback getMzblInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getJkdaInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getMzcfInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_Out_Hospital_RecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback uploadGrdaInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getZycfInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback upload_In_Hospital_RecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkMzOperationCompleted;
    
    /// <remarks/>
    public CHIService() {
        this.Url = "http://192.168.60.40:8085/jxcy/services/CHIService";
    }
    
    /// <remarks/>
    public event getYfjzInfoCompletedEventHandler getYfjzInfoCompleted;
    
    /// <remarks/>
    public event checkHthCompletedEventHandler checkHthCompleted;
    
    /// <remarks/>
    public event upload_Medical_InspectionInfoCompletedEventHandler upload_Medical_InspectionInfoCompleted;
    
    /// <remarks/>
    public event uploadMzInfoCompletedEventHandler uploadMzInfoCompleted;
    
    /// <remarks/>
    public event upload_Clinic_Medical_RecordsCompletedEventHandler upload_Clinic_Medical_RecordsCompleted;
    
    /// <remarks/>
    public event upload_Mzcf_RecordsCompletedEventHandler upload_Mzcf_RecordsCompleted;
    
    /// <remarks/>
    public event uploadCrbInfoCompletedEventHandler uploadCrbInfoCompleted;
    
    /// <remarks/>
    public event getZyBcInfoCompletedEventHandler getZyBcInfoCompleted;
    
    /// <remarks/>
    public event getPatientInfoCompletedEventHandler getPatientInfoCompleted;
    
    /// <remarks/>
    public event getMbInfoCompletedEventHandler getMbInfoCompleted;
    
    /// <remarks/>
    public event getZyryInfoCompletedEventHandler getZyryInfoCompleted;
    
    /// <remarks/>
    public event getZhxxCompletedEventHandler getZhxxCompleted;
    
    /// <remarks/>
    public event uploadMbInfoCompletedEventHandler uploadMbInfoCompleted;
    
    /// <remarks/>
    public event upload_To_Hospital_RecordsCompletedEventHandler upload_To_Hospital_RecordsCompleted;
    
    /// <remarks/>
    public event getTjrqCompletedEventHandler getTjrqCompleted;
    
    /// <remarks/>
    public event checkZyCompletedEventHandler checkZyCompleted;
    
    /// <remarks/>
    public event getZycyInfoCompletedEventHandler getZycyInfoCompleted;
    
    /// <remarks/>
    public event uploadZxsrCompletedEventHandler uploadZxsrCompleted;
    
    /// <remarks/>
    public event getTjInfoCompletedEventHandler getTjInfoCompleted;
    
    /// <remarks/>
    public event upload_Zycf_RecordsCompletedEventHandler upload_Zycf_RecordsCompleted;
    
    /// <remarks/>
    public event getMzblInfoCompletedEventHandler getMzblInfoCompleted;
    
    /// <remarks/>
    public event getJkdaInfoCompletedEventHandler getJkdaInfoCompleted;
    
    /// <remarks/>
    public event getMzcfInfoCompletedEventHandler getMzcfInfoCompleted;
    
    /// <remarks/>
    public event upload_Out_Hospital_RecordsCompletedEventHandler upload_Out_Hospital_RecordsCompleted;
    
    /// <remarks/>
    public event uploadGrdaInfoCompletedEventHandler uploadGrdaInfoCompleted;
    
    /// <remarks/>
    public event getZycfInfoCompletedEventHandler getZycfInfoCompleted;
    
    /// <remarks/>
    public event upload_In_Hospital_RecordsCompletedEventHandler upload_In_Hospital_RecordsCompleted;
    
    /// <remarks/>
    public event checkMzCompletedEventHandler checkMzCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getYfjzInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getYfjzInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetYfjzInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getYfjzInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetYfjzInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getYfjzInfoAsync(string in0) {
        this.getYfjzInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getYfjzInfoAsync(string in0, object userState) {
        if ((this.getYfjzInfoOperationCompleted == null)) {
            this.getYfjzInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetYfjzInfoOperationCompleted);
        }
        this.InvokeAsync("getYfjzInfo", new object[] {
                    in0}, this.getYfjzInfoOperationCompleted, userState);
    }
    
    private void OngetYfjzInfoOperationCompleted(object arg) {
        if ((this.getYfjzInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getYfjzInfoCompleted(this, new getYfjzInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string checkHth([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("checkHth", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckHth(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkHth", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcheckHth(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void checkHthAsync(string in0) {
        this.checkHthAsync(in0, null);
    }
    
    /// <remarks/>
    public void checkHthAsync(string in0, object userState) {
        if ((this.checkHthOperationCompleted == null)) {
            this.checkHthOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckHthOperationCompleted);
        }
        this.InvokeAsync("checkHth", new object[] {
                    in0}, this.checkHthOperationCompleted, userState);
    }
    
    private void OncheckHthOperationCompleted(object arg) {
        if ((this.checkHthCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkHthCompleted(this, new checkHthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_Medical_InspectionInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_Medical_InspectionInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_Medical_InspectionInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_Medical_InspectionInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_Medical_InspectionInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_Medical_InspectionInfoAsync(string in0) {
        this.upload_Medical_InspectionInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_Medical_InspectionInfoAsync(string in0, object userState) {
        if ((this.upload_Medical_InspectionInfoOperationCompleted == null)) {
            this.upload_Medical_InspectionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_Medical_InspectionInfoOperationCompleted);
        }
        this.InvokeAsync("upload_Medical_InspectionInfo", new object[] {
                    in0}, this.upload_Medical_InspectionInfoOperationCompleted, userState);
    }
    
    private void Onupload_Medical_InspectionInfoOperationCompleted(object arg) {
        if ((this.upload_Medical_InspectionInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_Medical_InspectionInfoCompleted(this, new upload_Medical_InspectionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string uploadMzInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("uploadMzInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadMzInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadMzInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnduploadMzInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void uploadMzInfoAsync(string in0) {
        this.uploadMzInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void uploadMzInfoAsync(string in0, object userState) {
        if ((this.uploadMzInfoOperationCompleted == null)) {
            this.uploadMzInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadMzInfoOperationCompleted);
        }
        this.InvokeAsync("uploadMzInfo", new object[] {
                    in0}, this.uploadMzInfoOperationCompleted, userState);
    }
    
    private void OnuploadMzInfoOperationCompleted(object arg) {
        if ((this.uploadMzInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadMzInfoCompleted(this, new uploadMzInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_Clinic_Medical_Records([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_Clinic_Medical_Records", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_Clinic_Medical_Records(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_Clinic_Medical_Records", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_Clinic_Medical_Records(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_Clinic_Medical_RecordsAsync(string in0) {
        this.upload_Clinic_Medical_RecordsAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_Clinic_Medical_RecordsAsync(string in0, object userState) {
        if ((this.upload_Clinic_Medical_RecordsOperationCompleted == null)) {
            this.upload_Clinic_Medical_RecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_Clinic_Medical_RecordsOperationCompleted);
        }
        this.InvokeAsync("upload_Clinic_Medical_Records", new object[] {
                    in0}, this.upload_Clinic_Medical_RecordsOperationCompleted, userState);
    }
    
    private void Onupload_Clinic_Medical_RecordsOperationCompleted(object arg) {
        if ((this.upload_Clinic_Medical_RecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_Clinic_Medical_RecordsCompleted(this, new upload_Clinic_Medical_RecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_Mzcf_Records([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_Mzcf_Records", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_Mzcf_Records(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_Mzcf_Records", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_Mzcf_Records(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_Mzcf_RecordsAsync(string in0) {
        this.upload_Mzcf_RecordsAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_Mzcf_RecordsAsync(string in0, object userState) {
        if ((this.upload_Mzcf_RecordsOperationCompleted == null)) {
            this.upload_Mzcf_RecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_Mzcf_RecordsOperationCompleted);
        }
        this.InvokeAsync("upload_Mzcf_Records", new object[] {
                    in0}, this.upload_Mzcf_RecordsOperationCompleted, userState);
    }
    
    private void Onupload_Mzcf_RecordsOperationCompleted(object arg) {
        if ((this.upload_Mzcf_RecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_Mzcf_RecordsCompleted(this, new upload_Mzcf_RecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string uploadCrbInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("uploadCrbInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadCrbInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadCrbInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnduploadCrbInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void uploadCrbInfoAsync(string in0) {
        this.uploadCrbInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void uploadCrbInfoAsync(string in0, object userState) {
        if ((this.uploadCrbInfoOperationCompleted == null)) {
            this.uploadCrbInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadCrbInfoOperationCompleted);
        }
        this.InvokeAsync("uploadCrbInfo", new object[] {
                    in0}, this.uploadCrbInfoOperationCompleted, userState);
    }
    
    private void OnuploadCrbInfoOperationCompleted(object arg) {
        if ((this.uploadCrbInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadCrbInfoCompleted(this, new uploadCrbInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getZyBcInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getZyBcInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetZyBcInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getZyBcInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetZyBcInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getZyBcInfoAsync(string in0) {
        this.getZyBcInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getZyBcInfoAsync(string in0, object userState) {
        if ((this.getZyBcInfoOperationCompleted == null)) {
            this.getZyBcInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZyBcInfoOperationCompleted);
        }
        this.InvokeAsync("getZyBcInfo", new object[] {
                    in0}, this.getZyBcInfoOperationCompleted, userState);
    }
    
    private void OngetZyBcInfoOperationCompleted(object arg) {
        if ((this.getZyBcInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getZyBcInfoCompleted(this, new getZyBcInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getPatientInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
        object[] results = this.Invoke("getPatientInfo", new object[] {
                    in0,
                    in1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPatientInfo(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPatientInfo", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetPatientInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getPatientInfoAsync(string in0, string in1) {
        this.getPatientInfoAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void getPatientInfoAsync(string in0, string in1, object userState) {
        if ((this.getPatientInfoOperationCompleted == null)) {
            this.getPatientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPatientInfoOperationCompleted);
        }
        this.InvokeAsync("getPatientInfo", new object[] {
                    in0,
                    in1}, this.getPatientInfoOperationCompleted, userState);
    }
    
    private void OngetPatientInfoOperationCompleted(object arg) {
        if ((this.getPatientInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPatientInfoCompleted(this, new getPatientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getMbInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getMbInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetMbInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getMbInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetMbInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getMbInfoAsync(string in0) {
        this.getMbInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getMbInfoAsync(string in0, object userState) {
        if ((this.getMbInfoOperationCompleted == null)) {
            this.getMbInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMbInfoOperationCompleted);
        }
        this.InvokeAsync("getMbInfo", new object[] {
                    in0}, this.getMbInfoOperationCompleted, userState);
    }
    
    private void OngetMbInfoOperationCompleted(object arg) {
        if ((this.getMbInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getMbInfoCompleted(this, new getMbInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getZyryInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getZyryInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetZyryInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getZyryInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetZyryInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getZyryInfoAsync(string in0) {
        this.getZyryInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getZyryInfoAsync(string in0, object userState) {
        if ((this.getZyryInfoOperationCompleted == null)) {
            this.getZyryInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZyryInfoOperationCompleted);
        }
        this.InvokeAsync("getZyryInfo", new object[] {
                    in0}, this.getZyryInfoOperationCompleted, userState);
    }
    
    private void OngetZyryInfoOperationCompleted(object arg) {
        if ((this.getZyryInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getZyryInfoCompleted(this, new getZyryInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getZhxx([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
        object[] results = this.Invoke("getZhxx", new object[] {
                    in0,
                    in1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetZhxx(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getZhxx", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetZhxx(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getZhxxAsync(string in0, string in1) {
        this.getZhxxAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void getZhxxAsync(string in0, string in1, object userState) {
        if ((this.getZhxxOperationCompleted == null)) {
            this.getZhxxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZhxxOperationCompleted);
        }
        this.InvokeAsync("getZhxx", new object[] {
                    in0,
                    in1}, this.getZhxxOperationCompleted, userState);
    }
    
    private void OngetZhxxOperationCompleted(object arg) {
        if ((this.getZhxxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getZhxxCompleted(this, new getZhxxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string uploadMbInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("uploadMbInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadMbInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadMbInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnduploadMbInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void uploadMbInfoAsync(string in0) {
        this.uploadMbInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void uploadMbInfoAsync(string in0, object userState) {
        if ((this.uploadMbInfoOperationCompleted == null)) {
            this.uploadMbInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadMbInfoOperationCompleted);
        }
        this.InvokeAsync("uploadMbInfo", new object[] {
                    in0}, this.uploadMbInfoOperationCompleted, userState);
    }
    
    private void OnuploadMbInfoOperationCompleted(object arg) {
        if ((this.uploadMbInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadMbInfoCompleted(this, new uploadMbInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_To_Hospital_Records([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_To_Hospital_Records", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_To_Hospital_Records(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_To_Hospital_Records", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_To_Hospital_Records(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_To_Hospital_RecordsAsync(string in0) {
        this.upload_To_Hospital_RecordsAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_To_Hospital_RecordsAsync(string in0, object userState) {
        if ((this.upload_To_Hospital_RecordsOperationCompleted == null)) {
            this.upload_To_Hospital_RecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_To_Hospital_RecordsOperationCompleted);
        }
        this.InvokeAsync("upload_To_Hospital_Records", new object[] {
                    in0}, this.upload_To_Hospital_RecordsOperationCompleted, userState);
    }
    
    private void Onupload_To_Hospital_RecordsOperationCompleted(object arg) {
        if ((this.upload_To_Hospital_RecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_To_Hospital_RecordsCompleted(this, new upload_To_Hospital_RecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getTjrq([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
        object[] results = this.Invoke("getTjrq", new object[] {
                    in0,
                    in1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTjrq(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTjrq", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetTjrq(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getTjrqAsync(string in0, string in1) {
        this.getTjrqAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void getTjrqAsync(string in0, string in1, object userState) {
        if ((this.getTjrqOperationCompleted == null)) {
            this.getTjrqOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTjrqOperationCompleted);
        }
        this.InvokeAsync("getTjrq", new object[] {
                    in0,
                    in1}, this.getTjrqOperationCompleted, userState);
    }
    
    private void OngetTjrqOperationCompleted(object arg) {
        if ((this.getTjrqCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTjrqCompleted(this, new getTjrqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string checkZy([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
        object[] results = this.Invoke("checkZy", new object[] {
                    in0,
                    in1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckZy(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkZy", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcheckZy(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void checkZyAsync(string in0, string in1) {
        this.checkZyAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void checkZyAsync(string in0, string in1, object userState) {
        if ((this.checkZyOperationCompleted == null)) {
            this.checkZyOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckZyOperationCompleted);
        }
        this.InvokeAsync("checkZy", new object[] {
                    in0,
                    in1}, this.checkZyOperationCompleted, userState);
    }
    
    private void OncheckZyOperationCompleted(object arg) {
        if ((this.checkZyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkZyCompleted(this, new checkZyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getZycyInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getZycyInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetZycyInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getZycyInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetZycyInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getZycyInfoAsync(string in0) {
        this.getZycyInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getZycyInfoAsync(string in0, object userState) {
        if ((this.getZycyInfoOperationCompleted == null)) {
            this.getZycyInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZycyInfoOperationCompleted);
        }
        this.InvokeAsync("getZycyInfo", new object[] {
                    in0}, this.getZycyInfoOperationCompleted, userState);
    }
    
    private void OngetZycyInfoOperationCompleted(object arg) {
        if ((this.getZycyInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getZycyInfoCompleted(this, new getZycyInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string uploadZxsr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("uploadZxsr", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadZxsr(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadZxsr", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnduploadZxsr(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void uploadZxsrAsync(string in0) {
        this.uploadZxsrAsync(in0, null);
    }
    
    /// <remarks/>
    public void uploadZxsrAsync(string in0, object userState) {
        if ((this.uploadZxsrOperationCompleted == null)) {
            this.uploadZxsrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadZxsrOperationCompleted);
        }
        this.InvokeAsync("uploadZxsr", new object[] {
                    in0}, this.uploadZxsrOperationCompleted, userState);
    }
    
    private void OnuploadZxsrOperationCompleted(object arg) {
        if ((this.uploadZxsrCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadZxsrCompleted(this, new uploadZxsrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getTjInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getTjInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTjInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTjInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetTjInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getTjInfoAsync(string in0) {
        this.getTjInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getTjInfoAsync(string in0, object userState) {
        if ((this.getTjInfoOperationCompleted == null)) {
            this.getTjInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTjInfoOperationCompleted);
        }
        this.InvokeAsync("getTjInfo", new object[] {
                    in0}, this.getTjInfoOperationCompleted, userState);
    }
    
    private void OngetTjInfoOperationCompleted(object arg) {
        if ((this.getTjInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTjInfoCompleted(this, new getTjInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_Zycf_Records([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_Zycf_Records", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_Zycf_Records(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_Zycf_Records", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_Zycf_Records(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_Zycf_RecordsAsync(string in0) {
        this.upload_Zycf_RecordsAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_Zycf_RecordsAsync(string in0, object userState) {
        if ((this.upload_Zycf_RecordsOperationCompleted == null)) {
            this.upload_Zycf_RecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_Zycf_RecordsOperationCompleted);
        }
        this.InvokeAsync("upload_Zycf_Records", new object[] {
                    in0}, this.upload_Zycf_RecordsOperationCompleted, userState);
    }
    
    private void Onupload_Zycf_RecordsOperationCompleted(object arg) {
        if ((this.upload_Zycf_RecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_Zycf_RecordsCompleted(this, new upload_Zycf_RecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getMzblInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getMzblInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetMzblInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getMzblInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetMzblInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getMzblInfoAsync(string in0) {
        this.getMzblInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getMzblInfoAsync(string in0, object userState) {
        if ((this.getMzblInfoOperationCompleted == null)) {
            this.getMzblInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMzblInfoOperationCompleted);
        }
        this.InvokeAsync("getMzblInfo", new object[] {
                    in0}, this.getMzblInfoOperationCompleted, userState);
    }
    
    private void OngetMzblInfoOperationCompleted(object arg) {
        if ((this.getMzblInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getMzblInfoCompleted(this, new getMzblInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getJkdaInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
        object[] results = this.Invoke("getJkdaInfo", new object[] {
                    in0,
                    in1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetJkdaInfo(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getJkdaInfo", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetJkdaInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getJkdaInfoAsync(string in0, string in1) {
        this.getJkdaInfoAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void getJkdaInfoAsync(string in0, string in1, object userState) {
        if ((this.getJkdaInfoOperationCompleted == null)) {
            this.getJkdaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJkdaInfoOperationCompleted);
        }
        this.InvokeAsync("getJkdaInfo", new object[] {
                    in0,
                    in1}, this.getJkdaInfoOperationCompleted, userState);
    }
    
    private void OngetJkdaInfoOperationCompleted(object arg) {
        if ((this.getJkdaInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getJkdaInfoCompleted(this, new getJkdaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getMzcfInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getMzcfInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetMzcfInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getMzcfInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetMzcfInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getMzcfInfoAsync(string in0) {
        this.getMzcfInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getMzcfInfoAsync(string in0, object userState) {
        if ((this.getMzcfInfoOperationCompleted == null)) {
            this.getMzcfInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMzcfInfoOperationCompleted);
        }
        this.InvokeAsync("getMzcfInfo", new object[] {
                    in0}, this.getMzcfInfoOperationCompleted, userState);
    }
    
    private void OngetMzcfInfoOperationCompleted(object arg) {
        if ((this.getMzcfInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getMzcfInfoCompleted(this, new getMzcfInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_Out_Hospital_Records([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_Out_Hospital_Records", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_Out_Hospital_Records(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_Out_Hospital_Records", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_Out_Hospital_Records(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_Out_Hospital_RecordsAsync(string in0) {
        this.upload_Out_Hospital_RecordsAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_Out_Hospital_RecordsAsync(string in0, object userState) {
        if ((this.upload_Out_Hospital_RecordsOperationCompleted == null)) {
            this.upload_Out_Hospital_RecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_Out_Hospital_RecordsOperationCompleted);
        }
        this.InvokeAsync("upload_Out_Hospital_Records", new object[] {
                    in0}, this.upload_Out_Hospital_RecordsOperationCompleted, userState);
    }
    
    private void Onupload_Out_Hospital_RecordsOperationCompleted(object arg) {
        if ((this.upload_Out_Hospital_RecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_Out_Hospital_RecordsCompleted(this, new upload_Out_Hospital_RecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string uploadGrdaInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("uploadGrdaInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadGrdaInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadGrdaInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnduploadGrdaInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void uploadGrdaInfoAsync(string in0) {
        this.uploadGrdaInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void uploadGrdaInfoAsync(string in0, object userState) {
        if ((this.uploadGrdaInfoOperationCompleted == null)) {
            this.uploadGrdaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadGrdaInfoOperationCompleted);
        }
        this.InvokeAsync("uploadGrdaInfo", new object[] {
                    in0}, this.uploadGrdaInfoOperationCompleted, userState);
    }
    
    private void OnuploadGrdaInfoOperationCompleted(object arg) {
        if ((this.uploadGrdaInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadGrdaInfoCompleted(this, new uploadGrdaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string getZycfInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("getZycfInfo", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetZycfInfo(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getZycfInfo", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetZycfInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getZycfInfoAsync(string in0) {
        this.getZycfInfoAsync(in0, null);
    }
    
    /// <remarks/>
    public void getZycfInfoAsync(string in0, object userState) {
        if ((this.getZycfInfoOperationCompleted == null)) {
            this.getZycfInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZycfInfoOperationCompleted);
        }
        this.InvokeAsync("getZycfInfo", new object[] {
                    in0}, this.getZycfInfoOperationCompleted, userState);
    }
    
    private void OngetZycfInfoOperationCompleted(object arg) {
        if ((this.getZycfInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getZycfInfoCompleted(this, new getZycfInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string upload_In_Hospital_Records([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
        object[] results = this.Invoke("upload_In_Hospital_Records", new object[] {
                    in0});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginupload_In_Hospital_Records(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("upload_In_Hospital_Records", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endupload_In_Hospital_Records(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void upload_In_Hospital_RecordsAsync(string in0) {
        this.upload_In_Hospital_RecordsAsync(in0, null);
    }
    
    /// <remarks/>
    public void upload_In_Hospital_RecordsAsync(string in0, object userState) {
        if ((this.upload_In_Hospital_RecordsOperationCompleted == null)) {
            this.upload_In_Hospital_RecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupload_In_Hospital_RecordsOperationCompleted);
        }
        this.InvokeAsync("upload_In_Hospital_Records", new object[] {
                    in0}, this.upload_In_Hospital_RecordsOperationCompleted, userState);
    }
    
    private void Onupload_In_Hospital_RecordsOperationCompleted(object arg) {
        if ((this.upload_In_Hospital_RecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.upload_In_Hospital_RecordsCompleted(this, new upload_In_Hospital_RecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ty.com/CHIService", ResponseNamespace="http://webservice.ty.com/CHIService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
    public string checkMz([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
        object[] results = this.Invoke("checkMz", new object[] {
                    in0,
                    in1});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckMz(string in0, string in1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkMz", new object[] {
                    in0,
                    in1}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcheckMz(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void checkMzAsync(string in0, string in1) {
        this.checkMzAsync(in0, in1, null);
    }
    
    /// <remarks/>
    public void checkMzAsync(string in0, string in1, object userState) {
        if ((this.checkMzOperationCompleted == null)) {
            this.checkMzOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckMzOperationCompleted);
        }
        this.InvokeAsync("checkMz", new object[] {
                    in0,
                    in1}, this.checkMzOperationCompleted, userState);
    }
    
    private void OncheckMzOperationCompleted(object arg) {
        if ((this.checkMzCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkMzCompleted(this, new checkMzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getYfjzInfoCompletedEventHandler(object sender, getYfjzInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getYfjzInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getYfjzInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void checkHthCompletedEventHandler(object sender, checkHthCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkHthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkHthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_Medical_InspectionInfoCompletedEventHandler(object sender, upload_Medical_InspectionInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_Medical_InspectionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_Medical_InspectionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void uploadMzInfoCompletedEventHandler(object sender, uploadMzInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uploadMzInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uploadMzInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_Clinic_Medical_RecordsCompletedEventHandler(object sender, upload_Clinic_Medical_RecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_Clinic_Medical_RecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_Clinic_Medical_RecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_Mzcf_RecordsCompletedEventHandler(object sender, upload_Mzcf_RecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_Mzcf_RecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_Mzcf_RecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void uploadCrbInfoCompletedEventHandler(object sender, uploadCrbInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uploadCrbInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uploadCrbInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getZyBcInfoCompletedEventHandler(object sender, getZyBcInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getZyBcInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getZyBcInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getPatientInfoCompletedEventHandler(object sender, getPatientInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPatientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPatientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getMbInfoCompletedEventHandler(object sender, getMbInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getMbInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getMbInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getZyryInfoCompletedEventHandler(object sender, getZyryInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getZyryInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getZyryInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getZhxxCompletedEventHandler(object sender, getZhxxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getZhxxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getZhxxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void uploadMbInfoCompletedEventHandler(object sender, uploadMbInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uploadMbInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uploadMbInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_To_Hospital_RecordsCompletedEventHandler(object sender, upload_To_Hospital_RecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_To_Hospital_RecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_To_Hospital_RecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getTjrqCompletedEventHandler(object sender, getTjrqCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTjrqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTjrqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void checkZyCompletedEventHandler(object sender, checkZyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkZyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkZyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getZycyInfoCompletedEventHandler(object sender, getZycyInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getZycyInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getZycyInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void uploadZxsrCompletedEventHandler(object sender, uploadZxsrCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uploadZxsrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uploadZxsrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getTjInfoCompletedEventHandler(object sender, getTjInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTjInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTjInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_Zycf_RecordsCompletedEventHandler(object sender, upload_Zycf_RecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_Zycf_RecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_Zycf_RecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getMzblInfoCompletedEventHandler(object sender, getMzblInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getMzblInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getMzblInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getJkdaInfoCompletedEventHandler(object sender, getJkdaInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getJkdaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getJkdaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getMzcfInfoCompletedEventHandler(object sender, getMzcfInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getMzcfInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getMzcfInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_Out_Hospital_RecordsCompletedEventHandler(object sender, upload_Out_Hospital_RecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_Out_Hospital_RecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_Out_Hospital_RecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void uploadGrdaInfoCompletedEventHandler(object sender, uploadGrdaInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uploadGrdaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uploadGrdaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void getZycfInfoCompletedEventHandler(object sender, getZycfInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getZycfInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getZycfInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void upload_In_Hospital_RecordsCompletedEventHandler(object sender, upload_In_Hospital_RecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class upload_In_Hospital_RecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal upload_In_Hospital_RecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void checkMzCompletedEventHandler(object sender, checkMzCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkMzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkMzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
