//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIS.EMR_BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HIS.EMR_BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;chs&gt;
        ///  &lt;table&gt;
        ///    &lt;row type=&quot;0&quot;&gt;
        ///      &lt;dahid&gt;档案号id&lt;/dahid&gt;
        ///      &lt;zs&gt;主诉&lt;/zs&gt;
        ///      &lt;xbs&gt;现病史&lt;/xbs&gt;
        ///      &lt;jws&gt;既往史&lt;/jws&gt;
        ///      &lt;jzs&gt;家族史&lt;/jzs&gt;
        ///      &lt;gms&gt;过敏史&lt;/gms&gt;
        ///      &lt;yjs&gt;月经史&lt;/yjs&gt;
        ///      &lt;hys&gt;婚育史&lt;/hys&gt;
        ///      &lt;tw&gt;体温&lt;/tw&gt;
        ///      &lt;hx&gt;呼吸&lt;/hx&gt;
        ///      &lt;mb&gt;脉搏&lt;/mb&gt;
        ///      &lt;ssy&gt;SBP&lt;/ssy&gt;
        ///      &lt;szy&gt;DBP&lt;/szy&gt;
        ///      &lt;tgjc&gt;其他体格检查信息&lt;/tgjc&gt;
        ///      &lt;hzjc&gt;辅助检查&lt;/hzjc&gt;
        ///      &lt;zd&gt;诊断&lt;/zd&gt;
        ///      &lt;zd2&gt;诊断2&lt;/zd2&gt;
        ///      &lt;zd3&gt;诊断3&lt;/zd3&gt;
        ///      &lt;zd4&gt;诊断4&lt;/zd4&gt;
        ///      &lt;zdqt&gt;其他诊断&lt;/zdqt&gt;
        ///      &lt;cf&gt;处方信息&lt;/cf&gt;
        ///      &lt;jz [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ClinicMedicalRecords {
            get {
                return ResourceManager.GetString("ClinicMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;chs&gt;
        ///  &lt;table&gt;
        ///    &lt;row  type=&quot;0&quot;&gt;
        ///      &lt;zyid&gt;住院号id &lt;/zyid&gt;
        ///      &lt;dahid&gt;档案号id&lt;/dahid&gt;
        ///      &lt;tw&gt;体温 &lt;/tw&gt;
        ///      &lt;hx&gt;呼吸&lt;/hx&gt;
        ///      &lt;mb&gt;脉搏&lt;/mb&gt;
        ///      &lt;ssy&gt;SBP&lt;/ssy&gt;
        ///      &lt;szy&gt;DBP&lt;/szy&gt;
        ///      &lt;tgjc&gt;体格检查&lt;/tgjc&gt;
        ///      &lt;hzjc&gt;辅助检查&lt;/hzjc&gt;
        ///      &lt;zd&gt;诊断&lt;/zd&gt;
        ///      &lt;cf&gt;处方&lt;/cf&gt;
        ///      &lt;qt&gt;其他&lt;/qt&gt;
        ///      &lt;zdqt&gt;其他诊断&lt;/zdqt&gt;
        ///      &lt;ryqk&gt;入院情况&lt;/ryqk&gt;
        ///      &lt;zdyj&gt;诊断依据&lt;/zdyj&gt;
        ///      &lt;jbzd&gt;鉴别诊断 &lt;/jbzd&gt;
        ///      &lt;jcrq&gt;检查日期&lt;/jcrq&gt;
        ///      &lt;jcys&gt;检查医生&lt;/jcys&gt;
        ///      &lt;jgdm&gt;机构代码&lt;/jgdm&gt;
        ///      &lt;djr&gt;登记人&lt;/djr&gt;
        ///      &lt;djrq [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InHospitalRecords {
            get {
                return ResourceManager.GetString("InHospitalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;chs&gt;
        ///  &lt;table&gt;
        ///    &lt;row type=&quot;0&quot;&gt;
        ///      &lt;cfbh&gt;处方编号&lt;/cfbh&gt;
        ///      &lt;dahid&gt;档案号id&lt;/dahid&gt;
        ///      &lt;jzsj&gt;就诊时间&lt;/jzsj&gt;
        ///      &lt;xmmc&gt; 项目名称&lt;/xmmc&gt;
        ///      &lt;gg&gt;规格&lt;/gg&gt;
        ///      &lt;cs&gt;产商&lt;/cs&gt;
        ///      &lt;ph&gt;批号&lt;/ph&gt;
        ///      &lt;sl&gt;数量&lt;/sl&gt;
        ///      &lt;dw&gt;单位&lt;/dw&gt;
        ///      &lt;dj&gt;单价&lt;/dj&gt;
        ///      &lt;yf&gt;用法&lt;/yf&gt;
        ///      &lt;yl&gt;用量&lt;/yl&gt;
        ///      &lt;pl&gt;频率&lt;/pl&gt;
        ///      &lt;djr&gt;登记人&lt;/djr&gt;
        ///      &lt;djrq&gt;登记日期&lt;/djrq&gt;
        ///      &lt;jgdm&gt;机构代码&lt;/jgdm&gt;
        ///      &lt;his_blbh&gt;病历编号&lt;/his_blbh&gt;
        ///    &lt;/row&gt;
        ///  &lt;/table&gt;
        ///&lt;/chs&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string MzcfRecords {
            get {
                return ResourceManager.GetString("MzcfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;chs&gt;
        ///  &lt;table&gt;
        ///    &lt;row  type=&quot;0&quot;&gt;
        ///      &lt;zyid&gt;住院ID&lt;/zyid&gt;
        ///      &lt;dahid&gt;档案号ID&lt;/dahid&gt;
        ///      &lt;zzys&gt;主治医生&lt;/zzys&gt;
        ///      &lt;ryqk&gt;入院情况&lt;/ryqk&gt;
        ///      &lt;cyrq&gt;出院日期&lt;/cyrq&gt;
        ///      &lt;cyqk&gt;出院情况&lt;/cyqk&gt;
        ///      &lt;cyzd&gt;出院诊断&lt;/cyzd&gt;
        ///      &lt;cyyz&gt;出院医嘱&lt;/cyyz&gt;
        ///      &lt;zdqt&gt;其他诊断&lt;/zdqt&gt;
        ///      &lt;qt&gt;其他&lt;/qt&gt;
        ///      &lt;zljg&gt;诊疗经过&lt;/zljg&gt;
        ///      &lt;jgdm&gt;医院代码&lt;/jgdm&gt;
        ///      &lt;djr&gt;登记人&lt;/djr&gt;
        ///      &lt;djrq&gt;登记日期&lt;/djrq&gt;
        ///    &lt;/row&gt;
        ///  &lt;/table&gt;
        ///&lt;/chs&gt; 的本地化字符串。
        /// </summary>
        internal static string OutHospitalRecords {
            get {
                return ResourceManager.GetString("OutHospitalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;chs&gt;
        ///  &lt;table&gt;
        ///    &lt;row  type=&quot;0&quot;&gt;
        ///      &lt;zyid&gt;住院ID&lt;/zyid&gt;
        ///      &lt;zyh&gt;住院号&lt;/zyh&gt;
        ///      &lt;dahid&gt;档案号ID&lt;/dahid&gt;
        ///      &lt;zs&gt;主诉&lt;/zs&gt;
        ///      &lt;xbs&gt;现病史&lt;/xbs&gt;
        ///      &lt;jws&gt;既往史&lt;/jws&gt;
        ///      &lt;jzs&gt;家族史&lt;/jzs&gt;
        ///      &lt;gms&gt;过敏史&lt;/gms&gt;
        ///      &lt;yjs&gt;月经史&lt;/yjs&gt;
        ///      &lt;hys&gt;婚育史&lt;/hys&gt;
        ///      &lt;zylx&gt;住院类型&lt;/zylx&gt;
        ///      &lt;fffs&gt;付费方式&lt;/fffs&gt;
        ///      &lt;ryrq&gt;入院时间&lt;/ryrq&gt;
        ///      &lt;ryqk&gt;入院情况&lt;/ryqk&gt;
        ///      &lt;ryzd&gt;入院诊断&lt;/ryzd&gt;
        ///      &lt;zdqt&gt;其他诊断&lt;/zdqt&gt;
        ///      &lt;ryks&gt;科室&lt;/ryks&gt;
        ///      &lt;ch&gt;床号&lt;/ch&gt;
        ///      &lt;zzys&gt;主治医生&lt;/zzys&gt;
        ///      &lt;qt&gt;其他&lt;/qt&gt;
        ///      &lt;jzyy [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ToHospitalRecords {
            get {
                return ResourceManager.GetString("ToHospitalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   &lt;chs&gt;
        ///    &lt;table&gt;
        ///      &lt;row type=&quot;0&quot;&gt;
        ///        &lt;CFBH&gt;处方编号&lt;/CFBH&gt;
        ///        &lt;DAHID&gt;档案号ID&lt;/DAHID&gt;
        ///        &lt;JZSJ&gt;就诊时间&lt;/JZSJ&gt;
        ///        &lt;XMMC&gt; 项目名称&lt;/XMMC&gt;
        ///        &lt;GG&gt;规格&lt;/GG&gt;
        ///        &lt;CS&gt;产商&lt;/CS&gt;
        ///        &lt;PH&gt;批号&lt;/PH&gt;
        ///        &lt;SL&gt;数量&lt;/SL&gt;
        ///        &lt;DW&gt;单位&lt;/DW&gt;
        ///        &lt;DJ&gt;单价&lt;/DJ&gt;
        ///        &lt;YF&gt;用法&lt;/YF&gt;
        ///        &lt;YL&gt;用量&lt;/YL&gt;
        ///        &lt;PL&gt;频率&lt;/PL&gt;
        ///        &lt;DJR&gt;登记人&lt;/DJR&gt;
        ///        &lt;DJRQ&gt;登记日期&lt;/DJRQ&gt;
        ///        &lt;JGDM&gt;机构代码&lt;/JGDM&gt;
        ///        &lt;HIS_BLBH&gt;病历编号&lt;/HIS_BLBH&gt;
        ///      &lt;/row&gt;
        ///    &lt;/table&gt;
        ///  &lt;/chs&gt;
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string ZycfRecords {
            get {
                return ResourceManager.GetString("ZycfRecords", resourceCulture);
            }
        }
    }
}
